import { Review } from "@/types";

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    userId: 'user1',
    userName: 'Nguyễn Thị Lan',
    rating: 5,
    comment: 'Túi rất đẹp, chất lượng tốt. Giao hàng nhanh chóng!',
    date: '2024-01-20',
    helpful: 12,
  },
  {
    id: '2',
    userId: 'user2',
    userName: 'Trần Văn Minh',
    rating: 4,
    comment: 'Sản phẩm đẹp như hình, giá hợp lý.',
    date: '2024-01-18',
    helpful: 8,
  },
  {
    id: '3',
    userId: 'user3',
    userName: 'Lê Thu Hà',
    rating: 5,
    comment: 'Rất hài lòng với sản phẩm. Sẽ mua thêm!',
    date: '2024-01-15',
    helpful: 15,
  },
  {
    id: '4',
    userId: 'user4',
    userName: 'Phạm Văn Hùng',
    rating: 3,
    comment: 'Sản phẩm ổn nhưng giá hơi cao.',
    date: '2024-01-12',
    helpful: 5,
  },
  {
    id: '5',
    userId: 'user5',
    userName: 'Hoàng Thị Mai',
    rating: 5,
    comment: 'Túi rất sang trọng, đúng như mô tả!',
    date: '2024-01-10',
    helpful: 20,
  },
  {
    id: '6',
    userId: 'user6',
    userName: 'Đỗ Minh Tuấn',
    rating: 4,
    comment: 'Chất lượng tốt, ship nhanh.',
    date: '2024-01-08',
    helpful: 7,
  },
  {
    id: '7',
    userId: 'user7',
    userName: 'Vũ Thu Hương',
    rating: 5,
    comment: 'Cực kỳ hài lòng! Sẽ giới thiệu bạn bè.',
    date: '2024-01-05',
    helpful: 18,
  },
  {
    id: '8',
    userId: 'user8',
    userName: 'Ngô Văn Long',
    rating: 2,
    comment: 'Màu sắc không giống hình.',
    date: '2024-01-03',
    helpful: 3,
  },
];